# Generated by Django 3.2.4 on 2021-06-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_auto_20210613_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
